//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetDetail
    {
        public string ASSET_ID { get; set; }
        public string ASSET_NAME { get; set; }
        public string ASSET_CODE { get; set; }
        public System.DateTime SUBPOENA_DATE { get; set; }
        public System.DateTime BOOKING_DATE { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public decimal ASSET_COST { get; set; }
        public string ASSET_STATE { get; set; }
        public decimal ASSET_DEPR { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
    }
}
