//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITOrgComs
    {
        public int IT_ORG_ID { get; set; }
        public System.DateTime ORG_COMS_DATE { get; set; }
        public Nullable<int> ORG_COMS { get; set; }
        public Nullable<decimal> ORG_IN_JOB { get; set; }
        public Nullable<decimal> ORG_WH_JOB { get; set; }
    }
}
