//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobMapping
    {
        public int JOB_MAPPING_ID { get; set; }
        public string JOB_NAME { get; set; }
        public string JOB_CAT1 { get; set; }
        public string JOB_CAT2 { get; set; }
        public string JOB_CAT3 { get; set; }
    }
}
