//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LawCompliance
    {
        public string LawUserID { get; set; }
        public string LawUserNO { get; set; }
        public string LawUserName { get; set; }
        public string LawUserDeptID { get; set; }
        public string LawUserDeptName { get; set; }
    }
}
