//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRight
    {
        public int MEMBER_RIGHT_ID { get; set; }
        public Nullable<int> MEMBER_RIGHT_CAT_ORDER { get; set; }
        public string MEMBER_RIGHT_CAT { get; set; }
        public string MEMBER_RIGHT_FUN { get; set; }
        public string MEMBER_RIGHT_NAME { get; set; }
        public Nullable<int> MEMBER_RIGHT_ORDER { get; set; }
        public Nullable<int> MEMBER_RIGHT_FLAG { get; set; }
        public string MEMBER_RIGHT_URL { get; set; }
        public Nullable<bool> MEMBER_RIGHT_IS_MENU { get; set; }
    }
}
