//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSP_CUBE_TIME_BY_DAY
    {
        public int TIME_ID { get; set; }
        public Nullable<System.DateTime> TIME_DATE { get; set; }
        public string TIME_DAY { get; set; }
        public string TIME_MONTH { get; set; }
        public Nullable<int> TIME_YEAR { get; set; }
        public Nullable<int> TIME_DAY_OF_MONTH { get; set; }
        public Nullable<int> TIME_WEEK_OF_YEAR { get; set; }
        public Nullable<int> TIME_MONTH_OF_YEAR { get; set; }
        public string TIME_QTR { get; set; }
        public Nullable<int> TIME_WORK_HOUR { get; set; }
    }
}
