//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectLog = new HashSet<ProjectLog>();
        }
    
        public string PrjID { get; set; }
        public string PrjType { get; set; }
        public string PrjName { get; set; }
        public string PriDes { get; set; }
        public string ReqID { get; set; }
        public string DeptID { get; set; }
        public string DisplayMAPrjOnUI { get; set; }
        public Nullable<decimal> FinishRate { get; set; }
        public Nullable<decimal> PlannedManMonth { get; set; }
        public Nullable<decimal> AccumulationHour { get; set; }
        public Nullable<int> TotalDocumentProduct { get; set; }
        public Nullable<int> ActualDocumentProduct { get; set; }
        public Nullable<int> PlannedBAFunctionPoint { get; set; }
        public Nullable<int> PlannedCloseFunctionPoint { get; set; }
        public Nullable<int> PlannedPEPFunctionPoint { get; set; }
        public string IsBuildBaseChange { get; set; }
        public string IsInfluenceTime { get; set; }
        public string IsCommitmentChange { get; set; }
        public string IsRiskItem { get; set; }
        public string IsRiskCountermeasure { get; set; }
        public string IsKeyManOnTime { get; set; }
        public string IsMemberTrain { get; set; }
        public Nullable<decimal> SPI { get; set; }
        public string PrjStatus { get; set; }
        public string NewPrjScale { get; set; }
        public string IsCMMIPrj { get; set; }
        public string IsOutsourcing { get; set; }
        public string IsITProject { get; set; }
        public Nullable<decimal> ImpactValue { get; set; }
        public Nullable<decimal> CIPercent { get; set; }
        public Nullable<decimal> AuditPercent { get; set; }
        public Nullable<int> CLF1 { get; set; }
        public Nullable<int> CLF2 { get; set; }
        public Nullable<int> CLF3 { get; set; }
        public Nullable<int> PRFNew { get; set; }
        public Nullable<int> PRFDelay { get; set; }
        public Nullable<int> PRFFinish { get; set; }
        public Nullable<int> PRFAll { get; set; }
        public Nullable<System.DateTime> PlannedStartDate { get; set; }
        public Nullable<System.DateTime> PlannedEndDate { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public Nullable<System.DateTime> PrjCloseDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LastModifyUser { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public string OldPrjID { get; set; }
        public string ThisWeekProgress { get; set; }
        public string NextWeekProgress { get; set; }
        public string OtherReportDesc { get; set; }
        public string CheckItemDesc { get; set; }
        public Nullable<int> RequireChangeSum { get; set; }
        public Nullable<int> RequireChangePlane { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectLog> ProjectLog { get; set; }
    }
}
