//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjDetailExcel
    {
        public System.DateTime PROJ_UPDATE_DATE { get; set; }
        public string PROJ_NAME { get; set; }
        public string PROJ_CODE { get; set; }
        public decimal PROJ_SPI { get; set; }
        public string PROJ_STATUS_FLAG { get; set; }
        public decimal PROJ_PLAN_WH { get; set; }
        public decimal PROJ_ACT_WH { get; set; }
        public decimal PROJ_PLAN_DUR { get; set; }
        public decimal PROJ_ACT_DUR { get; set; }
        public string PROJ_NOW_STATUS { get; set; }
        public string PROJ_OWNER { get; set; }
        public string PROJ_DEPT { get; set; }
        public string PROJ_TYPE { get; set; }
        public string PROJ_KICKOFF_DATE { get; set; }
        public string PROJ_ONLINE_DATE { get; set; }
        public string PROJ_ACTONLINE_DATE { get; set; }
        public string PROJ_MILESTONE_PCT { get; set; }
        public string PROJ_SPI_PRE { get; set; }
        public string PROJ_PMO_STATUS { get; set; }
        public string PROJ_PMO_RES { get; set; }
        public string PROJ_PMO_RPT { get; set; }
        public string PROJ_FP { get; set; }
        public string PROJ_CONT_NAME { get; set; }
        public string PROJ_BUDGET { get; set; }
        public string PROJ_CONT_AMT { get; set; }
        public string PROJ_CONT_AMT_PAY { get; set; }
        public string PROJ_CONT_AMT_PAID { get; set; }
        public string PROJ_PCT { get; set; }
        public string PROJ_ACT_PCT { get; set; }
        public string PROJ_ACT_WH_PCT { get; set; }
        public string PROJ_PRO_DEPT { get; set; }
        public string PROJ_PRO_USER { get; set; }
    }
}
