//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqAssn
    {
        public int REQ_ASSN_ID { get; set; }
        public Nullable<int> REQ_DETAIL_ID { get; set; }
        public Nullable<System.DateTime> REQ_ASSN_START { get; set; }
        public Nullable<System.DateTime> REQ_ASSN_FINISH { get; set; }
        public Nullable<decimal> REQ_ASSN_DUR { get; set; }
        public string REQ_TIME_CODE { get; set; }
        public Nullable<decimal> PLAN_WH { get; set; }
        public string EMP_ID { get; set; }
    }
}
