//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqDetail
    {
        public int REQ_DETAIL_ID { get; set; }
        public string REQ_ID { get; set; }
        public string REQ_DEPT_CODE { get; set; }
        public string REQ_SEC_CODE { get; set; }
        public string FORM_TYPE { get; set; }
        public string REQ_STATUS { get; set; }
        public string REQ_WORK_NAME { get; set; }
        public Nullable<System.DateTime> REQ_APPLY_DATE { get; set; }
        public Nullable<System.DateTime> REQ_CLOSE_DATE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_NAME { get; set; }
    }
}
