//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public string FORMNO { get; set; }
        public string ReqID { get; set; }
        public string FormType { get; set; }
        public string ApplicantDes { get; set; }
        public string ReqType { get; set; }
        public string ReqSubject { get; set; }
        public string ReqDes { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<System.DateTime> ExpectedFinishedDate { get; set; }
        public string ITDept { get; set; }
        public string MAProjectID { get; set; }
        public string ReqStatus { get; set; }
        public string ITAccepter { get; set; }
        public Nullable<System.DateTime> ITAcceptedDate { get; set; }
        public Nullable<int> AcceptType { get; set; }
        public string EstimateAccepter { get; set; }
        public Nullable<System.DateTime> EstimateAcceptDate { get; set; }
        public Nullable<int> EstimateType { get; set; }
        public string EstimateDesc { get; set; }
        public Nullable<int> FPA { get; set; }
        public Nullable<System.DateTime> PlannedStartDate { get; set; }
        public Nullable<System.DateTime> PlannedEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.DateTime> AcceptStartDate { get; set; }
        public Nullable<System.DateTime> AcceptEndDate { get; set; }
        public Nullable<System.DateTime> ReqCloseDate { get; set; }
        public string ReqCloseDes { get; set; }
        public string IsWithdraw { get; set; }
        public Nullable<System.DateTime> ReqCancelDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LastModifyUser { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public string OldReqID { get; set; }
        public Nullable<System.DateTime> ITResponse { get; set; }
        public string CheckStatus { get; set; }
        public string LawUserNO { get; set; }
        public string IsTDC { get; set; }
        public string IsTDCDes { get; set; }
        public Nullable<System.DateTime> QuestionSendDate { get; set; }
        public Nullable<bool> OverDueReplan { get; set; }
        public Nullable<System.DateTime> ProdDate { get; set; }
        public Nullable<System.DateTime> ProdPlanDate { get; set; }
        public string ReqCmt { get; set; }
        public Nullable<System.DateTime> UriStartDate { get; set; }
        public Nullable<System.DateTime> UriFinishDate { get; set; }
        public Nullable<decimal> UriDur { get; set; }
        public Nullable<decimal> UriWorkPct { get; set; }
        public Nullable<int> ModifiedCount { get; set; }
        public Nullable<int> Ominute { get; set; }
        public Nullable<int> nTimes { get; set; }
        public string ITUnitID { get; set; }
        public string ITSigned { get; set; }
        public string PIPNo { get; set; }
        public Nullable<int> URScore1 { get; set; }
        public Nullable<int> URScore2 { get; set; }
        public Nullable<int> URScore3 { get; set; }
        public Nullable<int> URScore { get; set; }
        public Nullable<int> ITScore1 { get; set; }
        public Nullable<int> ITScore2 { get; set; }
        public Nullable<int> ITScore { get; set; }
        public Nullable<int> TTLScore { get; set; }
        public string iGotData { get; set; }
        public Nullable<decimal> PlannedWorkHour { get; set; }
        public string MARK1 { get; set; }
        public string MARK2 { get; set; }
        public string MARK3 { get; set; }
        public Nullable<int> MARK4 { get; set; }
        public Nullable<int> MARK5 { get; set; }
        public string SetupProjectID { get; set; }
    }
}
