//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHandler
    {
        public string ReqID { get; set; }
        public string EmpID { get; set; }
        public string IsRequestOwner { get; set; }
        public string IsEnabled { get; set; }
        public string WorkStatus { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ItemTypeID { get; set; }
        public string ItemLabel { get; set; }
        public Nullable<decimal> WorkPlanDur { get; set; }
        public Nullable<System.DateTime> WorkPlanStartDate { get; set; }
        public Nullable<System.DateTime> WorkPlanEndDate { get; set; }
        public Nullable<decimal> WorkPlanPct { get; set; }
    }
}
