//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RequireSystemEntities : DbContext
    {
        public RequireSystemEntities()
            : base("name=RequireSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<EPMReportingTime> EPMReportingTime { get; set; }
        public virtual DbSet<Estimate> Estimate { get; set; }
        public virtual DbSet<ITEmployee> ITEmployee { get; set; }
        public virtual DbSet<LawCompliance> LawCompliance { get; set; }
        public virtual DbSet<MSP_CUBE_TIME_BY_DAY> MSP_CUBE_TIME_BY_DAY { get; set; }
        public virtual DbSet<PersonalWeeklyReport> PersonalWeeklyReport { get; set; }
        public virtual DbSet<PersonalWeeklyReportProjectItem> PersonalWeeklyReportProjectItem { get; set; }
        public virtual DbSet<PersonalWeeklyReportRequestItem> PersonalWeeklyReportRequestItem { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectLog> ProjectLog { get; set; }
        public virtual DbSet<ProjectRiskItem> ProjectRiskItem { get; set; }
        public virtual DbSet<ProjectRiskItemLog> ProjectRiskItemLog { get; set; }
        public virtual DbSet<ProjectTeamMember> ProjectTeamMember { get; set; }
        public virtual DbSet<ProjectTeamMemberRole> ProjectTeamMemberRole { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<QuestionMember> QuestionMember { get; set; }
        public virtual DbSet<QuestionResponse> QuestionResponse { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<RequestAttachment> RequestAttachment { get; set; }
        public virtual DbSet<RequestHandler> RequestHandler { get; set; }
        public virtual DbSet<RequestType> RequestType { get; set; }
        public virtual DbSet<RiskType> RiskType { get; set; }
        public virtual DbSet<TimeSheetActualItem> TimeSheetActualItem { get; set; }
        public virtual DbSet<TimeSheetCmt> TimeSheetCmt { get; set; }
        public virtual DbSet<TimeSheetItemType> TimeSheetItemType { get; set; }
        public virtual DbSet<TimeSheetPlanItem> TimeSheetPlanItem { get; set; }
        public virtual DbSet<tmpDNEED> tmpDNEED { get; set; }
        public virtual DbSet<WBSItem> WBSItem { get; set; }
        public virtual DbSet<WBSItemLog> WBSItemLog { get; set; }
        public virtual DbSet<ApplicantInfo> ApplicantInfo { get; set; }
        public virtual DbSet<ApplyMember> ApplyMember { get; set; }
        public virtual DbSet<AssetDetail> AssetDetail { get; set; }
        public virtual DbSet<BudgetDetail> BudgetDetail { get; set; }
        public virtual DbSet<BugFormAmort> BugFormAmort { get; set; }
        public virtual DbSet<CostCategory> CostCategory { get; set; }
        public virtual DbSet<CostDept> CostDept { get; set; }
        public virtual DbSet<CostDetail> CostDetail { get; set; }
        public virtual DbSet<CostMapping> CostMapping { get; set; }
        public virtual DbSet<DataModifyFormAmort> DataModifyFormAmort { get; set; }
        public virtual DbSet<DeptAmortFlag> DeptAmortFlag { get; set; }
        public virtual DbSet<DeptAmortFlag2> DeptAmortFlag2 { get; set; }
        public virtual DbSet<DeptWH> DeptWH { get; set; }
        public virtual DbSet<EPMAssn> EPMAssn { get; set; }
        public virtual DbSet<EPMTimesheetWH> EPMTimesheetWH { get; set; }
        public virtual DbSet<ITOrg> ITOrg { get; set; }
        public virtual DbSet<ITOrgComs> ITOrgComs { get; set; }
        public virtual DbSet<ITOrgRes> ITOrgRes { get; set; }
        public virtual DbSet<ITYearBudget> ITYearBudget { get; set; }
        public virtual DbSet<ITYearCost> ITYearCost { get; set; }
        public virtual DbSet<JobMapping> JobMapping { get; set; }
        public virtual DbSet<JobRule> JobRule { get; set; }
        public virtual DbSet<L1Mgr> L1Mgr { get; set; }
        public virtual DbSet<L1MgrDeptMapping> L1MgrDeptMapping { get; set; }
        public virtual DbSet<LaborCostRuleMapping> LaborCostRuleMapping { get; set; }
        public virtual DbSet<MemberRight> MemberRight { get; set; }
        public virtual DbSet<MemberRole> MemberRole { get; set; }
        public virtual DbSet<MemberRoleRight> MemberRoleRight { get; set; }
        public virtual DbSet<MonthWorkDay> MonthWorkDay { get; set; }
        public virtual DbSet<OrganizeData> OrganizeData { get; set; }
        public virtual DbSet<ProjAmort> ProjAmort { get; set; }
        public virtual DbSet<ProjDetail> ProjDetail { get; set; }
        public virtual DbSet<ProjDetailExcel> ProjDetailExcel { get; set; }
        public virtual DbSet<ProjSysMapping> ProjSysMapping { get; set; }
        public virtual DbSet<ReqAssn> ReqAssn { get; set; }
        public virtual DbSet<ReqDept> ReqDept { get; set; }
        public virtual DbSet<ReqDetail> ReqDetail { get; set; }
        public virtual DbSet<ReqTimesheetWH> ReqTimesheetWH { get; set; }
        public virtual DbSet<Serial> Serial { get; set; }
        public virtual DbSet<SysStatus> SysStatus { get; set; }
        public virtual DbSet<SystemMember> SystemMember { get; set; }
        public virtual DbSet<TimeCat1> TimeCat1 { get; set; }
        public virtual DbSet<TimeCat2> TimeCat2 { get; set; }
        public virtual DbSet<TimeCat3> TimeCat3 { get; set; }
        public virtual DbSet<TimeCode> TimeCode { get; set; }
        public virtual DbSet<TimeCodePublish> TimeCodePublish { get; set; }
        public virtual DbSet<TimesheetRes> TimesheetRes { get; set; }
        public virtual DbSet<webloginb> webloginb { get; set; }
        public virtual DbSet<YearPlanProj> YearPlanProj { get; set; }
        public virtual DbSet<YearPlanProjRes> YearPlanProjRes { get; set; }
        public virtual DbSet<YearPlanRes> YearPlanRes { get; set; }
    }
}
