//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeCodePublish
    {
        public int TIME_CODE_PUBLISH_ID { get; set; }
        public System.DateTime TIME_CODE_YEAR { get; set; }
        public int TIME_CAT1_ID { get; set; }
        public string TIME_CAT1_NAME { get; set; }
        public int TIME_CAT1_ORDER { get; set; }
        public string TIME_CAT2_NAME { get; set; }
        public int TIME_CAT2_ID { get; set; }
        public bool TIME_CAT2_PRD { get; set; }
        public int TIME_CAT2_ORDER { get; set; }
        public int TIME_CAT3_ID { get; set; }
        public string TIME_CAT3_NAME { get; set; }
        public int TIME_CAT3_ORDER { get; set; }
        public int TIME_CODE_ID { get; set; }
        public string TIME_CODE { get; set; }
        public string TIME_CODE_NAME { get; set; }
        public string TIME_CODE_DESC1 { get; set; }
        public string TIME_CODE_DESC2 { get; set; }
        public int TIME_CODE_ORDER { get; set; }
    }
}
