//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBSItem
    {
        public int ItemSN { get; set; }
        public string PrjID { get; set; }
        public int ItemID { get; set; }
        public string ItemDes { get; set; }
        public Nullable<System.DateTime> PlannedStartDate { get; set; }
        public Nullable<System.DateTime> PlannedEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<int> FinishRate { get; set; }
        public Nullable<int> DealPayment { get; set; }
        public Nullable<int> PaidPayment { get; set; }
        public string DocumentProduct { get; set; }
        public Nullable<decimal> SPI { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> WBSPath { get; set; }
    }
}
