//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webloginb
    {
        public string Col001 { get; set; }
        public string Col002 { get; set; }
        public string Col003 { get; set; }
        public string Col004 { get; set; }
        public string Col005 { get; set; }
        public string Col006 { get; set; }
        public string Col007 { get; set; }
        public string Col008 { get; set; }
        public string Col009 { get; set; }
        public string Col010 { get; set; }
        public string Col011 { get; set; }
        public string Col012 { get; set; }
        public string Col013 { get; set; }
        public string Col014 { get; set; }
        public string Col015 { get; set; }
        public string Col016 { get; set; }
        public string Col017 { get; set; }
        public Nullable<int> Col018 { get; set; }
        public string Col019 { get; set; }
        public Nullable<decimal> Col020 { get; set; }
        public Nullable<int> Col021 { get; set; }
        public string Col022 { get; set; }
        public string Col023 { get; set; }
        public string Col024 { get; set; }
        public string Col025 { get; set; }
        public string Col026 { get; set; }
        public string Col027 { get; set; }
        public string Col028 { get; set; }
        public string Col029 { get; set; }
        public string Col030 { get; set; }
        public string Col031 { get; set; }
        public string Col032 { get; set; }
        public string Col033 { get; set; }
        public string Col034 { get; set; }
        public string Email { get; set; }
    }
}
