//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearPlanProjRes
    {
        public int YEAR_PLAN_PROJ_RES_ID { get; set; }
        public Nullable<System.DateTime> PLAN_YEAR_MONTH { get; set; }
        public Nullable<int> IT_ORG_ID { get; set; }
        public Nullable<int> YEAR_PLAN_RES_ID { get; set; }
        public Nullable<int> YEAR_PLAN_PROJ_ID { get; set; }
        public Nullable<decimal> RES_PLAN_PCT { get; set; }
    }
}
